/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stream */
        get: operations["get_stream_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recording/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recording Start */
        post: operations["post_recording_start_recording_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recording/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recording Stop */
        post: operations["post_recording_stop_recording_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DetectionModel */
        DetectionModel: {
            /** Tracker Id */
            tracker_id: number;
            /** Label */
            label: string;
            /** Thumbnail */
            thumbnail: string | null;
        };
        /** InstrumentReportModel */
        InstrumentReportModel: {
            /** Tracker Id */
            tracker_id: number;
            /** Label */
            label: string;
            /**
             * Completeness
             * @enum {string}
             */
            completeness: "present" | "missing";
            /** Usage */
            usage: components["schemas"]["UsageWindowModel"][];
        };
        /** InstrumentStatusModel */
        InstrumentStatusModel: {
            /** Tracker Id */
            tracker_id: number;
            /** Label */
            label: string;
            /** On Table */
            on_table: boolean;
            /** Off Since S */
            off_since_s: number | null;
            /** Pickup Count */
            pickup_count: number;
            /** Thumbnail */
            thumbnail: string | null;
        };
        /** RecordingStatus */
        RecordingStatus: {
            /** Started At */
            started_at: string;
            /** Elapsed S */
            elapsed_s: number;
            /** On Table Count */
            on_table_count: number;
            /** Instruments */
            instruments: components["schemas"]["InstrumentStatusModel"][];
        };
        /** ReportResponse */
        ReportResponse: {
            /** Started At */
            started_at: string;
            /** Stopped At */
            stopped_at: string;
            /** Duration S */
            duration_s: number;
            /** Model Version */
            model_version: string;
            /** Instruments */
            instruments: components["schemas"]["InstrumentReportModel"][];
        };
        /** SetupStatus */
        SetupStatus: {
            /** Detected Count */
            detected_count: number;
            /** Stable For S */
            stable_for_s: number;
            /** Detections */
            detections: components["schemas"]["DetectionModel"][];
        };
        /** StartResponse */
        StartResponse: {
            /** Started At */
            started_at: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "setup" | "recording" | "finished";
            /**
             * Capture Health
             * @enum {string}
             */
            capture_health: "ok" | "stalled";
            /** Model Version */
            model_version: string;
            setup: components["schemas"]["SetupStatus"] | null;
            recording: components["schemas"]["RecordingStatus"] | null;
        };
        /** UsageWindowModel */
        UsageWindowModel: {
            /** Off S */
            off_s: number;
            /** On S */
            on_s: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_stream_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post_recording_start_recording_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartResponse"];
                };
            };
        };
    };
    post_recording_stop_recording_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
        };
    };
    get_report_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
        };
    };
}
